### ISSUE TITLE
Question 5

### ISSUE THREAD

**Issue by yekcodertester** [AmirMahdyTurani/paya#1]
سلام من یکی از رقیب هاتون هستم امسال (البته این اکانت گیتهاب اصلیم نیست). میخواستم بهتون ایمیل بزنم ولی دیدم ایمیلی نزاشتید مجبور شدم اینجا ایشو باز کنم. به نظر من سوال ۵ مشکل داره، یا حداقل مثالش غلطه. میخواستم ببینم شما هم موافقید؟ چون ما هم خیلی وقته بقیه سوالارو حل کردیم ولی سوال ۵ رو هر چی فکر میکنم مثالی که زده منطقی به نظر نمیاد

**Comment by AmirMahdyTurani** [comment]
سلام @yekcodertester خیلی ممنون که issue باز کردی. بله درسته مثالی که زده توی پی دی اف نادرست هست. خیلی خوشحال شدم ولی با توجه به حساسیت مسابقه این ریپازیتوری گیت هاب تحت لایسنس هست :)) باز هم ممنون خوشحال میشم بیشتر آشنا بشیم.
